import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { formatCurrency as formatCurrencyUtil, WORLD_CURRENCIES } from '../lib/formatters';

export type Language = 'id' | 'en';

export const translations = {
  id: {
    // App & Tagline
    appTitle: 'SakuKu',
    appTagline: 'Keuangan Simpel & Fun',

    // Header & Modes
    allModes: 'Semua Mode',
    all: 'Semua',
    personal: 'Pribadi',
    business: 'Bisnis / UMKM',
    personalCash: 'Kas Pribadi',
    businessCash: 'Kas Bisnis / UMKM',

    // Bottom Navigation
    navHome: 'Beranda',
    navTransactions: 'Transaksi',
    navBudget: 'Anggaran',
    navRecord: 'Catat',
    navReports: 'Laporan',
    navSettings: 'Pengaturan',
    navProfile: 'Akun Kas',

    // Dashboard / Home
    totalBalance: 'Total Saldo Keuangan',
    accounts: 'Akun',
    personalMode: 'Mode Pribadi',
    businessMode: 'Mode Bisnis',
    allMode: 'Semua Mode',
    includesPersonalAndBusiness: 'Termasuk Kas Pribadi, Bank, & Unit Bisnis UMKM',
    cashTypeBusiness: 'Kas Bisnis',
    cashTypePersonal: 'Pribadi',
    netBalance: 'Total Saldo Keuangan',
    totalIncome: 'Pemasukan',
    totalExpense: 'Pengeluaran',
    monthlyCashFlow: 'Arus Kas Bulan Ini',
    incomeToday: 'Pemasukan Hari Ini',
    expenseToday: 'Pengeluaran Hari Ini',
    incomeThisMonth: 'Pemasukan Bulan Ini',
    expenseThisMonth: 'Pengeluaran Bulan Ini',
    incomeTotalSummary: 'Total Pemasukan',
    expenseTotalSummary: 'Total Pengeluaran',
    summaryTodayHeader: 'Ringkasan Hari Ini',
    summaryMonthHeader: 'Ringkasan Bulan Ini',
    summaryTotalHeader: 'Ringkasan Total',
    autoThisMonthTag: 'Auto: Bulan Ini',
    btnFilterToday: 'Hari Ini',
    btnFilterMonth: 'Bulan Ini',
    btnFilterAll: 'Semua',
    viewDetails: 'Lihat Detail',
    confirmDeleteTxHeader: 'Konfirmasi Hapus Transaksi',
    confirmDeleteTxDesc: 'Apakah Anda yakin ingin menghapus transaksi ini? Data akan dihapus secara permanen dari daftar, saldo akun, dan semua laporan.',
    deletePermanently: 'Hapus Permanen',
    transactions: 'Transaksi',
    quickActions: 'Aksi Cepat',
    addIncome: 'Kas Masuk (+)',
    addExpense: 'Kas Keluar (-)',
    scanReceipt: 'Pindai Struk AI',
    recentTransactions: 'Transaksi Terakhir',
    latest5Transactions: '5 Transaksi Terakhir',
    seeAll: 'Lihat Semua',
    noTransactions: 'Belum ada transaksi. Klik tombol (+) untuk mencatat.',
    noTransactionsInMode: 'Belum ada transaksi tercatat untuk mode ini.',
    today: 'Hari ini',
    yesterday: 'Kemarin',

    // Transactions View
    searchPlaceholder: 'Cari transaksi, toko, atau catatan...',
    filterAll: 'Semua',
    filterAllTypes: 'Semua Tipe',
    filterIncome: 'Pemasukan',
    filterExpense: 'Pengeluaran',
    incomeLabel: 'Kas Masuk',
    expenseLabel: 'Kas Keluar',
    deleteTx: 'Hapus Transaksi',
    confirmDeleteTx: 'Apakah Anda yakin ingin menghapus transaksi ini?',
    confirmDeleteTxAlert: 'Apakah Anda yakin ingin menghapus transaksi ini? Saldo akun akan diperbarui.',
    noTxFound: 'Tidak ada transaksi ditemukan',
    noTxFoundSub: 'Coba ubah kata kunci pencarian atau filter mode.',
    addTxBtn: 'Tambah Transaksi',

    // Budget View
    budgetTitle: 'Anggaran & Batas Pengeluaran',
    budgetSubtitle: 'Kelola batas belanja bulanan agar tidak boros',
    budgetBannerTitle: 'Perencanaan Anggaran',
    budgetTag: 'UMKM & Personal',
    budgetSub: 'Fleksibel tambah / kurangi pos anggaran biaya operasional & belanja',
    createBudgetBtn: 'Buat Anggaran',
    addBudget: 'Atur Anggaran',
    categoryBudget: 'Anggaran per Kategori',
    spent: 'Terpakai',
    remaining: 'Sisa',
    overBudget: 'Melebihi Anggaran!',
    setBudgetModalTitle: 'Atur Batas Anggaran Bulanan',
    saveBudget: 'Simpan Anggaran',
    noBudgetTitle: 'Belum Ada Perencanaan Anggaran',
    noBudgetSub: 'Perencanaan anggaran bersifat fleksibel. Anda dapat menambah atau mengurangi pos anggaran usaha (stok, gaji, sewa, operasional) maupun pribadi sesuai kebutuhan.',
    createFlexibleBudgetBtn: 'Buat Anggaran Fleksibel',
    realizedVsPlanned: 'Realisasi Pos Anggaran:',
    used: 'Terpakai',
    remainingPlan: 'Sisa Rencana:',
    plannedLines: 'Pos Anggaran Terencana',
    plannedLinesCount: 'Pos',
    accordingToPlan: 'Sesuai Perencanaan',
    exceedsTarget: 'Melebihi Target',
    difference: 'Selisih:',
    unplannedExpenseTitle: 'Pengeluaran di Luar Rencana',
    unplannedExpenseSub: 'Berikut pengeluaran yang tercatat di periode ini namun tidak dimasukkan ke dalam pos anggaran awal:',
    createFlexibleBudgetModalTitle: 'Buat Perencanaan Anggaran Fleksibel',
    modalBudgetSub: 'Tambah / kurangi pos anggaran biaya sesuai skala usaha & kebutuhan',
    budgetNameLabel: 'Nama Perencanaan Anggaran:',
    budgetNamePlaceholder: 'Contoh: Anggaran Operasional UMKM - Agustus',
    financialModeLabel: 'Mode Keuangan:',
    budgetTypeLabel: 'Pilihan Jenis Anggaran (Tipe Pos):',
    incomeType: '📈 Pemasukan',
    expenseType: '📉 Pengeluaran',
    allTypes: '🔄 Semua Jenis',
    realizationDateLabel: '📅 Tgl Rencana Realisasi:',
    startPeriod: 'Mulai Periode:',
    endPeriod: 'Selesai Periode:',
    budgetLinesLabel: 'Pos-Pos Anggaran',
    loadAllCategoriesBtn: '+ Muat Semua Kategori',
    newBudgetLineBtn: 'Tambah Pos Anggaran Baru',
    selectFromList: '📋 Pilih Dropdown',
    typeManually: '✏️ Ketik Manual',
    typeNewPosOption: '➕ + Ketik Pos Baru Manual...',
    customPosPlaceholder: 'Misal: Tabungan Umroh, Beli Mesin, Listrik...',
    customPosAutoSaveHint: '✨ Pos baru ini otomatis tersimpan ke database & muncul di pilihan dropdown berikutnya.',
    totalBudgetPlan: 'Total Rencana Anggaran:',
    plannedBalanceLabel: 'Saldo Rencana (Pemasukan - Pengeluaran):',
    totalPlannedExpense: 'Total Pengeluaran:',
    totalPlannedIncome: 'Total Pemasukan:',
    qtyLabel: 'Jml (Qty)',
    itemPriceLabel: 'Harga Satuan',
    totalPriceLabel: 'Total Harga',
    cancelBtn: 'Batal',
    savePlanBtn: 'Simpan Perencanaan',

    // Budget Reminders
    reminderTitle: 'Pengingat Jatuh Tempo & Target Anggaran',
    reminderAlertBanner: 'Pusat Pengingat Jatuh Tempo',
    reminderActiveAlert: 'Perhatian! Ada item anggaran yang perlu diperhatikan / jatuh tempo',
    reminderEnableToggle: 'Aktifkan Pengingat (Reminder)',
    reminderDateLabel: 'Tanggal Jatuh Tempo / Evaluasi:',
    reminderNoteLabel: 'Catatan Pengingat:',
    reminderNotePlaceholder: 'Contoh: Bayar tagihan listrik / Pembelian stok bahan baku',
    reminderTestSoundBtn: 'Uji Suara Bel (Ringing) 🔔',
    reminderDueToday: 'Jatuh Tempo Hari Ini',
    reminderOverdue: 'Terlewat Jatuh Tempo',
    reminderUpcoming: 'Pengingat Mendatang',
    reminderSetBtn: 'Set Pengingat',
    reminderEditTitle: 'Atur Pengingat Item Anggaran',
    reminderMarkDone: 'Selesai / Sudah Dibayar',
    reminderMarkPending: 'Tunda Pengingat',

    // Reports View
    reportsTitle: 'Laporan & Analisis Keuangan',
    reportsSubtitle: 'Grafik rekapitulasi pemasukan vs pengeluaran',
    cashflowOverview: 'Ringkasan Arus Kas',
    personalVsBusiness: 'Pribadi vs Bisnis',
    categoryBreakdown: 'Distribusi Pengeluaran',
    printReport: 'Cetak Laporan PDF/Print',
    downloadCashBookA4: 'Cetak Buku Kas A4',
    cashBookSub: 'Rekap Laporan Keuangan Cetak / PDF Lengkap',
    printBtn: 'Cetak',
    offlineStorage: 'Penyimpanan & Privasi Data',
    offlineStorageSub: 'Data disimpan lokal di HP Anda (TIDAK diunggah ke server pihak ketiga). Safe & Private.',
    periodDaily: 'Harian',
    periodWeekly: 'Mingguan',
    periodMonthly: 'Bulanan',
    periodYearly: 'Tahunan',
    reportPeriod: 'Periode Laporan',
    comparativeAnalysis: 'Analisis Komparasi Periode',
    last7DaysHistory: 'Riwayat 7 Hari Terakhir',
    last4WeeksHistory: 'Riwayat 4 Minggu Terakhir',
    last6MonthsHistory: 'Riwayat 6 Bulan Terakhir',
    last3YearsHistory: 'Riwayat 3 Tahun Terakhir',
    thisWeek: 'Minggu Ini',
    lastWeek: 'Minggu Lalu',
    planVsActual: 'Rencana vs Realisasi',
    categoryExpenses: 'Pengeluaran per Kategori',
    netCashFlow: 'Selisih Arus Kas (Net Cashflow)',

    // Add Transaction Modal
    selectInputMethod: 'Pilih Metode Catat Transaksi',
    selectInputSubtitle: 'Metode dibuat terpisah agar cepat, praktis & tidak membingungkan',
    selectInputMethodHeader: 'Pilih Metode Catat Transaksi',
    cameraAndUploadHeader: 'Kamera & Unggah Dokumen',
    geminiScanHeader: 'Pemindaian AI Gemini',
    selectStatementTxHeader: 'Pilih Transaksi Mutasi',
    recordFormHeader: 'Formulir Catat Transaksi',
    appSubtitleTag: 'SakuKu — Pencatatan Keuangan Praktis',
    selectFavInputMethod: 'Pilih Metode Input Favorit Anda',
    methodsSeparatedSubtitle: 'Metode dibuat terpisah agar cepat, praktis & tidak membingungkan',
    receiptCardTitle: '📸 Foto Struk & Catatan',
    receiptCardBadge: 'Kamera HP',
    receiptCardDesc: 'Foto langsung struk belanja, bon, nota, atau catatan tulisan tangan',
    bankStatementCardTitle: '📱 Screenshot',
    bankStatementCardBadge: 'Galeri Foto',
    bankStatementCardDesc: 'Pilih foto screenshot dari galeri (mutasi bank, e-wallet, QRIS, atau bukti bayar/pengeluaran)',
    handwrittenCardTitle: '✍️ Tulisan Tangan',
    handwrittenCardBadge: 'Kamera HP',
    handwrittenCardDesc: 'Langsung buka kamera untuk foto buku kas / catatan tertulis tangan',
    manualCardTitle: '✏️ Input Form Manual',
    manualCardBadge: 'Formulir Cepat',
    manualCardDesc: 'Ketik manual nominal, kas pribadi/bisnis, & deskripsi transaksi',
    webDesktopAltOption: 'Opsi Alternatif Web / Desktop:',
    openLiveWebCamera: 'Buka Live Web Camera',
    testAiPrefix: 'Tes AI:',
    positionDocHere: 'Posisikan Struk / Dokumen di sini',
    openHpCamera: 'Buka Kamera HP',
    selectFromGallery: 'Pilih dari Galeri',
    analyzingDocAiTitle: 'Menganalisis Dokumen AI',
    analyzingDocAiDesc: 'AI Gemini Vision sedang membaca nominal, tanggal, dan kategori transaksi...',
    aiFoundTxMsg: 'AI berhasil menemukan {count} transaksi mutasi',
    checkTxToSave: 'Centang transaksi yang ingin Anda simpan ke dalam catatan SakuKu:',
    saveStatementToAccount: 'Simpan Mutasi ke Akun:',
    saveCountMutations: 'Simpan ({count}) Mutasi',
    modeManualTag: 'Mode: Input Manual',
    modeAiScanTag: 'Mode: Hasil Pemindaian AI',
    step1DirectionHeader: '1. Pilihan Arah Uang:',
    step2AccountHeader: '2. Pilihan Kas Keuangan (Pribadi vs Bisnis):',
    step3DetailsHeader: '3. Baris Input Detail Transaksi:',
    personalWalletNote: 'Catatan Dompet & Pribadi',
    businessLabelPrefix: 'Bisnis',
    geminiScanResultHeader: 'Hasil Pindai AI Gemini',
    retakePhotoBtn: 'Foto Ulang',
    descPlaceholder: 'Contoh: Belanja stok toko, Makan siang, Pembayaran sewa',
    receiptPhoto: 'Foto Struk Belanja',
    receiptSub: 'Langsung buka kamera untuk foto struk Indomaret, minimarket, bon',
    bankStatement: 'Screenshot Mutasi Bank',
    statementSub: 'Langsung buka galeri untuk screenshot mutasi BCA, Mandiri, GoPay/OVO',
    handwrittenNotes: 'Tulisan Tangan',
    handwrittenSub: 'Langsung buka kamera untuk foto buku kas / catatan tertulis tangan',
    manualEntry: 'Input Form Manual',
    manualSub: 'Ketik manual nominal, kas pribadi/bisnis, & deskripsi transaksi',
    hpCamera: 'Kamera HP',
    photoGallery: 'Galeri Foto',
    quickForm: 'Formulir Cepat',
    orWebCamera: 'Opsi Alternatif Web / Desktop:',
    openLiveCamera: 'Buka Live Web Camera',
    aiSampleTest: 'Tes AI:',
    backToMethod: '← Kembali ke Pilih Metode',
    backToOtherMethod: '← Pilih Metode Input Lain',
    scanResultAI: 'Hasil Pindai AI Gemini',
    rephoto: 'Foto Ulang',
    saveTransaction: 'Simpan Transaksi',
    saveIncome: 'Simpan Kas Masuk (+)',
    saveExpense: 'Simpan Kas Keluar (-)',
    amountLabel: 'Nominal Transaksi (Rp):',
    descriptionLabel: 'Keterangan / Deskripsi:',
    categoryLabel: 'Kategori:',
    categoryIn: 'Masuk',
    categoryOut: 'Keluar',
    dateLabel: 'Tanggal & Waktu:',
    accountLabel: 'Kas / Rekening:',
    moneyDirection: 'Pilihan Arah Uang:',
    cashSelection: 'Pilihan Kas Keuangan (Pribadi vs Bisnis):',
    incomeStorageLocation: 'Lokasi Pemasukan Disimpan (Kas Kontan / Bank A / Bank B):',
    incomeAccountSelect: 'Pilih Kas Kontan, Bank A, Bank B, atau E-Wallet Tujuan:',
    quickAddAccount: '+ Tambah Lokasi / Rekening Bank Baru',
    selectSpecificAccount: 'Pilih Rekening / Akun Spesifik:',
    chooseYourBusiness: 'Pilih Bisnis Anda (Langsung ke Unit Bisnis):',

    // Settings (Pengaturan)
    settingsHeaderTitle: 'Pengaturan & Sistem',
    settingsHeaderSub: 'Konfigurasi aplikasi, langganan, keamanan & data',
    subTabSubscription: 'Langganan',
    subTabApp: 'Aplikasi',
    subTabBackup: 'Backup',
    subTabInfo: 'Info',
    androidAppTitle: 'Aplikasi Android Mobile Native',
    androidAppSub: 'Aplikasi SakuKu telah dikonfigurasi penuh sebagai Aplikasi Android Mobile (APK/PWA Standalone)',
    androidDownloadApk: 'Pasang / Install di HP Android',
    androidApkGuideTitle: 'Panduan Install ke HP Android (APK / PWA)',
    activePlan: 'Paket Aktif Anda',
    vipUnlimited: 'SakuKu PRO Unlimited',
    vipActiveDuration: 'Masa Aktif VIP: Aktif (Seumur Hidup / AI Studio)',
    subscriptionTiers: 'Pilihan Paket Langganan Aplikasi:',
    freePlan: 'SakuKu Basic Free',
    freePlanDesc: '10 scan foto struk/bulan, max 1 bisnis UMKM, catat harian standar',
    freePlanPrice: 'Rp 0',
    yearlyPlan: 'SakuKu PRO Tahunan',
    yearlyPlanDesc: 'Scan AI Tanpa Batas, Multi-Bisnis UMKM A,B,C, D, Rekap Laporan Keuangan',
    yearlyPlanPrice: 'Rp 19.000',
    yearlyPlanUnit: '/bulan (Rp 228rb/th)',
    statusVipActive: 'Status VIP PRO Aktif',
    appPreferences: 'Preferensi & Keamanan Aplikasi',
    appTheme: 'Tema Tampilan UI',
    appThemeSub: 'Pilih mode terang, gelap, atau ikuti pengaturan sistem',
    themeLight: 'Terang',
    themeDark: 'Gelap',
    themeSystem: 'Sistem',
    appLanguage: 'Bahasa Aplikasi / App Language',
    mainCurrency: 'Mata Uang Utama',
    currencyFormat: 'Format nominal transaksi',
    dailyReminder: 'Pengingat Catat Kas Harian',
    dailyReminderSub: 'Notifikasi pengingat jam 08:00 & 20:00',
    pinLock: 'Kunci PIN / Biometrik App',
    pinLockSub: 'Minta PIN saat membuka aplikasi',
    soundEffects: 'Efek Suara & Animasi Fun',
    soundEffectsSub: 'Animasi tombol & getaran interaktif',
    backupExport: 'Manajemen Backup & Ekspor Data',
    exportExcel: 'Ekspor Laporan ke Excel/CSV',
    exportExcelSub: 'Unduh data transaksi Laporan Keuangan lengkap',
    cloudBackup: 'Backup Otomatis Ke Cloud SakuKu',
    cloudBackupSub: 'Simpan cadangan data agar aman jika HP berganti',
    resetData: 'Reset & Pulihkan Data',
    resetDataSub: 'Mengembalikan data contoh sampel awal (Kas Tunai, Rekening BCA, Kas Toko Bisnis A).',
    resetButton: 'Reset Data Sampel',
    appVersion: 'SakuKu Financial Pro v2.4.0',
    appAboutText: 'Aplikasi Pencatatan Keuangan Praktis & Fun untuk Kas Pribadi, Rekening Bank, dan Unit Bisnis UMKM.',
    helpAndCommunity: 'Bantuan & Komunitas:',
    csWhatsApp: 'CS WhatsApp',
    guideFaq: 'Panduan & FAQ',

    // Profile / Accounts Management (Saya)
    profileTitle: 'Profil & Rekening Keuangan',
    profileSubtitle: 'Kelola dompet pribadi, rekening bank, & kas bisnis',
    manageAccountsTitle: 'Kelola Akun Keuangan',
    manageAccountsSub: 'Pribadi, Bisnis/UMKM (Dapat lebih dari 1), atau Gabungan',
    addAccountBtn: 'Tambah Akun',
    allAccountsFilter: 'Semua Akun',
    noAccountsFound: 'Belum ada akun untuk kategori ini. Klik "Tambah Akun" untuk membuat akun baru.',
    accountNumberLabel: 'No. Rek:',
    accountBalanceLabel: 'Saldo:',
    resetSampleTitle: 'Reset Data & Contoh',
    resetSampleSub: 'Mengembalikan data awal sampel (Akun Pribadi, beberapa Akun Bisnis UMKM, dan Akun Gabungan).',
    footerText: 'SakuKu - Keuangan Simpel & Menyenangkan',
    footerSub: 'Dukungan Multi-Bisnis UMKM, Pribadi & Gabungan • AI Vision Scanner',
    editAccountModalTitle: 'Edit Akun Keuangan',
    addAccountModalTitle: 'Tambah Akun Baru',
    accountScopeLabel: 'Peruntukan Akun:',
    scopePersonalSub: 'Gunakan untuk pencatatan keperluan pribadi.',
    scopeBusinessSub: 'Gunakan khusus untuk operasional bisnis / UMKM.',
    scopeCombinedSub: 'Digunakan bersama untuk transaksi pribadi maupun bisnis.',
    businessNameLabel: 'Nama Bisnis / Unit Usaha:',
    businessNamePlaceholder: 'Contoh: Toko Sembako, Laundry Express, Olshop Baju',
    selectRegisteredBusiness: 'Pilih dari bisnis terdaftar:',
    accountNameLabel: 'Nama Akun:',
    accountNamePlaceholder: 'Contoh: Kas Toko, Bank BCA, ShopeePay',
    accountTypeLabel: 'Jenis Akun:',
    cashTypeOpt: 'Kas Tunai',
    bankTypeOpt: 'Rekening Bank',
    ewalletTypeOpt: 'E-Wallet (GoPay, OVO, ShopeePay, DANA)',
    accountNumOptLabel: 'Nomor Rekening / HP (Opsional):',
    initialBalanceLabel: 'Saldo Awal (Rp):',
    accountsList: 'Daftar Kas & Rekening',
    addAccount: '+ Tambah Rekening / Kas',
    editAccount: 'Edit Rekening',
    accountName: 'Nama Rekening / Kas',
    accountType: 'Tipe Rekening',
    initialBalance: 'Saldo Awal',
    scope: 'Peruntukan',
    cashType: 'Kas Tunai',
    bankType: 'Rekening Bank',
    walletType: 'E-Wallet',
    businessType: 'Kas Bisnis',
    saveAccount: 'Simpan Rekening',

    // Toast Messages
    dataExported: 'Data berhasil diekspor ke file Excel/CSV!',
    backupCompleted: 'Backup Cloud selesai disimpan dengan aman!',
    langChanged: 'Bahasa diubah ke Bahasa Indonesia',
  },
  en: {
    // App & Tagline
    appTitle: 'SakuKu',
    appTagline: 'Simple & Fun Finance',

    // Header & Modes
    allModes: 'All Modes',
    all: 'All',
    personal: 'Personal',
    business: 'Business / SME',
    personalCash: 'Personal Cash',
    businessCash: 'Business / SME Cash',

    // Bottom Navigation
    navHome: 'Home',
    navTransactions: 'Transactions',
    navBudget: 'Budget',
    navRecord: 'Record',
    navReports: 'Reports',
    navSettings: 'Settings',
    navProfile: 'Accounts',

    // Dashboard / Home
    totalBalance: 'Total Net Balance',
    accounts: 'Accounts',
    personalMode: 'Personal Mode',
    businessMode: 'Business Mode',
    allMode: 'All Modes',
    includesPersonalAndBusiness: 'Includes Personal Cash, Bank, & SME Units',
    cashTypeBusiness: 'Business Cash',
    cashTypePersonal: 'Personal',
    netBalance: 'Total Net Balance',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expenses',
    monthlyCashFlow: 'Cash Flow This Month',
    incomeToday: "Today's Income",
    expenseToday: "Today's Expenses",
    incomeThisMonth: 'Income This Month',
    expenseThisMonth: 'Expenses This Month',
    incomeTotalSummary: 'Total Income',
    expenseTotalSummary: 'Total Expenses',
    summaryTodayHeader: "Today's Summary",
    summaryMonthHeader: 'This Month Summary',
    summaryTotalHeader: 'Total Summary',
    autoThisMonthTag: 'Auto: This Month',
    btnFilterToday: 'Today',
    btnFilterMonth: 'This Month',
    btnFilterAll: 'All',
    viewDetails: 'View Details',
    confirmDeleteTxHeader: 'Confirm Delete Transaction',
    confirmDeleteTxDesc: 'Are you sure you want to delete this transaction? Data will be permanently removed from lists, account balances, and reports.',
    deletePermanently: 'Delete Permanently',
    transactions: 'Transactions',
    quickActions: 'Quick Actions',
    addIncome: 'Income (+)',
    addExpense: 'Expense (-)',
    scanReceipt: 'AI Scan Receipt',
    recentTransactions: 'Recent Transactions',
    latest5Transactions: '5 Latest Transactions',
    seeAll: 'View All',
    noTransactions: 'No transactions recorded yet. Tap (+) to record one.',
    noTransactionsInMode: 'No transactions recorded yet for this mode.',
    today: 'Today',
    yesterday: 'Yesterday',

    // Transactions View
    searchPlaceholder: 'Search transactions, merchants, or notes...',
    filterAll: 'All',
    filterAllTypes: 'All Types',
    filterIncome: 'Income',
    filterExpense: 'Expense',
    incomeLabel: 'Money In',
    expenseLabel: 'Money Out',
    deleteTx: 'Delete Transaction',
    confirmDeleteTx: 'Are you sure you want to delete this transaction?',
    confirmDeleteTxAlert: 'Are you sure you want to delete this transaction? Account balance will be updated.',
    noTxFound: 'No transactions found',
    noTxFoundSub: 'Try changing search query or mode filter.',
    addTxBtn: 'Add Transaction',

    // Budget View
    budgetTitle: 'Budget & Spending Limits',
    budgetSubtitle: 'Manage monthly spending caps to stay on track',
    budgetBannerTitle: 'Budget Planning',
    budgetTag: 'SME & Personal',
    budgetSub: 'Flexible management of operational & shopping budget lines',
    createBudgetBtn: 'Create Budget',
    addBudget: 'Set Budget',
    categoryBudget: 'Category Budgets',
    spent: 'Spent',
    remaining: 'Remaining',
    overBudget: 'Over Budget!',
    setBudgetModalTitle: 'Set Monthly Budget Cap',
    saveBudget: 'Save Budget',
    noBudgetTitle: 'No Budget Plan Created',
    noBudgetSub: 'Budget planning is flexible. You can add or adjust business expense caps (stock, salary, rent) or personal expenses as needed.',
    createFlexibleBudgetBtn: 'Create Flexible Budget',
    realizedVsPlanned: 'Budget Realization:',
    used: 'Used',
    remainingPlan: 'Remaining Plan:',
    plannedLines: 'Planned Budget Lines',
    plannedLinesCount: 'Lines',
    accordingToPlan: 'According to Plan',
    exceedsTarget: 'Over Target',
    difference: 'Difference:',
    unplannedExpenseTitle: 'Unplanned Expenses',
    unplannedExpenseSub: 'The following expenses were recorded in this period but were not in the initial budget plan:',
    createFlexibleBudgetModalTitle: 'Create Flexible Budget Plan',
    modalBudgetSub: 'Add or adjust budget items based on business scale and needs',
    budgetNameLabel: 'Budget Plan Name:',
    budgetNamePlaceholder: 'e.g. Operational Budget - August',
    financialModeLabel: 'Financial Mode:',
    budgetTypeLabel: 'Budget Type Selection:',
    incomeType: '📈 Income',
    expenseType: '📉 Expense',
    allTypes: '🔄 All Types',
    realizationDateLabel: '📅 Target Realization Date:',
    startPeriod: 'Start Period:',
    endPeriod: 'End Period:',
    budgetLinesLabel: 'Budget Lines',
    loadAllCategoriesBtn: '+ Load All Categories',
    newBudgetLineBtn: 'Add New Budget Line',
    selectFromList: '📋 Select Dropdown',
    typeManually: '✏️ Type Manually',
    typeNewPosOption: '➕ + Type New Budget Line Manually...',
    customPosPlaceholder: 'e.g., Umrah Savings, New Equipment, Electricity...',
    customPosAutoSaveHint: '✨ This new item will be auto-saved to database for future dropdown selections.',
    totalBudgetPlan: 'Total Planned Budget:',
    plannedBalanceLabel: 'Planned Balance (Income - Expense):',
    totalPlannedExpense: 'Total Expense:',
    totalPlannedIncome: 'Total Income:',
    qtyLabel: 'Qty',
    itemPriceLabel: 'Item Price',
    totalPriceLabel: 'Total Price',
    cancelBtn: 'Cancel',
    savePlanBtn: 'Save Budget Plan',

    // Budget Reminders
    reminderTitle: 'Due Date & Target Budget Reminders',
    reminderAlertBanner: 'Due Date Reminder Hub',
    reminderActiveAlert: 'Attention! Budget items need your attention or are due today',
    reminderEnableToggle: 'Enable Reminder Alert',
    reminderDateLabel: 'Due Date / Evaluation Date:',
    reminderNoteLabel: 'Reminder Note:',
    reminderNotePlaceholder: 'e.g., Pay electricity bill / Purchase inventory stock',
    reminderTestSoundBtn: 'Test Bell Ring Sound 🔔',
    reminderDueToday: 'Due Today',
    reminderOverdue: 'Overdue',
    reminderUpcoming: 'Upcoming Reminder',
    reminderSetBtn: 'Set Reminder',
    reminderEditTitle: 'Manage Budget Item Reminder',
    reminderMarkDone: 'Mark Completed / Paid',
    reminderMarkPending: 'Postpone Reminder',

    // Reports View
    reportsTitle: 'Financial Reports & Analytics',
    reportsSubtitle: 'Income vs expense cashflow charts',
    cashflowOverview: 'Cash Flow Overview',
    personalVsBusiness: 'Personal vs Business',
    categoryBreakdown: 'Expense Breakdown',
    printReport: 'Export / Print PDF Report',
    downloadCashBookA4: 'Print A4 Cash Book',
    cashBookSub: 'Complete Financial Statement PDF / Print Export',
    printBtn: 'Print',
    offlineStorage: 'Data Storage & Privacy',
    offlineStorageSub: 'Data is stored locally on your device (NOT uploaded to third-party servers). Safe & Private.',
    periodDaily: 'Daily',
    periodWeekly: 'Weekly',
    periodMonthly: 'Monthly',
    periodYearly: 'Yearly',
    reportPeriod: 'Report Period',
    comparativeAnalysis: 'Period Comparative Analysis',
    last7DaysHistory: 'Last 7 Days History',
    last4WeeksHistory: 'Last 4 Weeks History',
    last6MonthsHistory: 'Last 6 Months History',
    last3YearsHistory: 'Last 3 Years History',
    thisWeek: 'This Week',
    lastWeek: 'Last Week',
    planVsActual: 'Plan vs Actual',
    categoryExpenses: 'Category Expenses',
    netCashFlow: 'Net Cash Flow',

    // Add Transaction Modal
    selectInputMethod: 'Select Transaction Input Method',
    selectInputSubtitle: 'Methods are separated for fast, practical & clear entry',
    selectInputMethodHeader: 'Select Transaction Input Method',
    cameraAndUploadHeader: 'Camera & Document Upload',
    geminiScanHeader: 'Gemini AI Scanning',
    selectStatementTxHeader: 'Select Statement Transactions',
    recordFormHeader: 'Transaction Input Form',
    appSubtitleTag: 'SakuKu — Practical Financial Bookkeeping',
    selectFavInputMethod: 'Choose Your Favorite Input Method',
    methodsSeparatedSubtitle: 'Methods are separated for fast, practical & clear entry',
    receiptCardTitle: '📸 Photo (Receipt & Notes)',
    receiptCardBadge: 'Mobile Camera',
    receiptCardDesc: 'Snap photo of shopping receipt, invoice, or handwritten note',
    bankStatementCardTitle: '📱 Screenshot',
    bankStatementCardBadge: 'Photo Gallery',
    bankStatementCardDesc: 'Select screenshot from gallery (bank statement, e-wallet, QRIS, or payment/expense proof)',
    handwrittenCardTitle: '✍️ Handwritten Notes',
    handwrittenCardBadge: 'Mobile Camera',
    handwrittenCardDesc: 'Directly open camera for cash ledger books or handwritten notes',
    manualCardTitle: '✏️ Manual Form Input',
    manualCardBadge: 'Quick Form',
    manualCardDesc: 'Manually type amount, personal/business cash account, & notes',
    webDesktopAltOption: 'Web / Desktop Alternative Option:',
    openLiveWebCamera: 'Open Live Web Camera',
    testAiPrefix: 'AI Test:',
    positionDocHere: 'Position Receipt / Document here',
    openHpCamera: 'Open Mobile Camera',
    selectFromGallery: 'Select from Gallery',
    analyzingDocAiTitle: 'Analyzing Document with AI',
    analyzingDocAiDesc: 'Gemini Vision AI is scanning amount, date, and category...',
    aiFoundTxMsg: 'AI successfully found {count} statement transactions',
    checkTxToSave: 'Check the transactions you want to save into SakuKu:',
    saveStatementToAccount: 'Save Statement to Account:',
    saveCountMutations: 'Save ({count}) Transactions',
    modeManualTag: 'Mode: Manual Entry',
    modeAiScanTag: 'Mode: AI Scan Result',
    step1DirectionHeader: '1. Money Flow Direction:',
    step2AccountHeader: '2. Account Scope (Personal vs Business):',
    step3DetailsHeader: '3. Transaction Detail Inputs:',
    personalWalletNote: 'Personal Wallet & Expense Notes',
    businessLabelPrefix: 'Business',
    geminiScanResultHeader: 'Gemini AI Scan Result',
    retakePhotoBtn: 'Retake Photo',
    descPlaceholder: 'e.g. Stock purchases, Lunch, Rent payment',
    receiptPhoto: 'Shopping Receipt Photo',
    receiptSub: 'Directly open camera for supermarket, store, or cafe receipts',
    bankStatement: 'Bank Statement Screenshot',
    statementSub: 'Directly open gallery for bank statement screenshots or e-wallets',
    handwrittenNotes: 'Handwritten Notes',
    handwrittenSub: 'Directly open camera for ledger books / handwritten log notes',
    manualEntry: 'Manual Form Entry',
    manualSub: 'Manually type amount, cash account, and transaction notes',
    hpCamera: 'Mobile Camera',
    photoGallery: 'Photo Gallery',
    quickForm: 'Quick Form',
    orWebCamera: 'Web / Desktop Alternative Option:',
    openLiveCamera: 'Open Live Web Camera',
    aiSampleTest: 'AI Test:',
    backToMethod: '← Back to Method Selection',
    backToOtherMethod: '← Select Other Input Method',
    scanResultAI: 'Gemini AI Scan Result',
    rephoto: 'Retake Photo',
    saveTransaction: 'Save Transaction',
    saveIncome: 'Save Money In (+)',
    saveExpense: 'Save Money Out (-)',
    amountLabel: 'Transaction Amount:',
    descriptionLabel: 'Description / Note:',
    categoryLabel: 'Category:',
    categoryIn: 'Income',
    categoryOut: 'Expense',
    dateLabel: 'Date & Time:',
    accountLabel: 'Cash / Account:',
    moneyDirection: 'Flow Direction:',
    cashSelection: 'Account Scope (Personal vs Business):',
    incomeStorageLocation: 'Income Storage Location (Cash / Bank A / Bank B):',
    incomeAccountSelect: 'Select Cash, Bank A, Bank B, or E-Wallet Destination:',
    quickAddAccount: '+ Add New Bank / Cash Location',
    selectSpecificAccount: 'Select Specific Account:',
    chooseYourBusiness: 'Select Your Business Unit:',

    // Settings (Pengaturan)
    settingsHeaderTitle: 'Settings & Preferences',
    settingsHeaderSub: 'App configuration, subscription, security & data',
    subTabSubscription: 'Subscription',
    subTabApp: 'App',
    subTabBackup: 'Backup',
    subTabInfo: 'Info',
    androidAppTitle: 'Native Android Mobile App',
    androidAppSub: 'SakuKu is fully configured as a Standalone Android Mobile App (APK / PWA)',
    androidDownloadApk: 'Install / Add to Android Phone',
    androidApkGuideTitle: 'Android Installation Guide (APK / Standalone)',
    activePlan: 'Your Active Plan',
    vipUnlimited: 'SakuKu PRO Unlimited',
    vipActiveDuration: 'VIP Access: Active (Lifetime / AI Studio)',
    subscriptionTiers: 'Available Subscription Plans:',
    freePlan: 'SakuKu Basic Free',
    freePlanDesc: '10 AI receipt scans/month, max 1 business unit, standard tracking',
    freePlanPrice: '$0',
    yearlyPlan: 'SakuKu PRO Yearly',
    yearlyPlanDesc: 'Unlimited AI Scans, Multi-Business A,B,C, D, Financial Statement Export',
    yearlyPlanPrice: '$1.50',
    yearlyPlanUnit: '/month ($18/year)',
    statusVipActive: 'VIP PRO Status Active',
    appPreferences: 'App Preferences & Security',
    appTheme: 'UI Theme Mode',
    appThemeSub: 'Switch between light, dark, or follow device system settings',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    appLanguage: 'App Language / Bahasa',
    mainCurrency: 'Main Currency',
    currencyFormat: 'Format for financial amounts',
    dailyReminder: 'Daily Bookkeeping Reminder',
    dailyReminderSub: 'Push notifications at 08:00 & 20:00',
    pinLock: 'App PIN / Biometric Lock',
    pinLockSub: 'Require PIN code upon opening app',
    soundEffects: 'Fun Sound Effects & Haptics',
    soundEffectsSub: 'Interactive button effects & vibration feedback',
    backupExport: 'Data Backup & Export Management',
    exportExcel: 'Export Reports to Excel/CSV',
    exportExcelSub: 'Download comprehensive financial transaction records',
    cloudBackup: 'Auto Cloud Backup to SakuKu',
    cloudBackupSub: 'Secure cloud sync to protect your records across devices',
    resetData: 'Reset & Restore Data',
    resetDataSub: 'Restores initial sample data (Cash, Bank Account, Store A).',
    resetButton: 'Reset Sample Data',
    appVersion: 'SakuKu Financial Pro v2.4.0',
    appAboutText: 'Practical & Fun Financial Bookkeeping App for Personal Cash, Bank Accounts, and SME Business Units.',
    helpAndCommunity: 'Help & Support:',
    csWhatsApp: 'WhatsApp Support',
    guideFaq: 'User Guide & FAQ',

    // Profile / Accounts Management (Saya)
    profileTitle: 'Financial Accounts & Profile',
    profileSubtitle: 'Manage personal wallets, bank accounts, & business cash',
    manageAccountsTitle: 'Manage Financial Accounts',
    manageAccountsSub: 'Personal, Business/SME (Multiple allowed), or Combined',
    addAccountBtn: 'Add Account',
    allAccountsFilter: 'All Accounts',
    noAccountsFound: 'No accounts found for this filter. Click "Add Account" to create a new account.',
    accountNumberLabel: 'Acc No:',
    accountBalanceLabel: 'Balance:',
    resetSampleTitle: 'Reset Sample Data',
    resetSampleSub: 'Restores initial sample data (Personal, SME Business Units, and Combined).',
    footerText: 'SakuKu - Simple & Fun Finance',
    footerSub: 'SME Multi-Business Support, Personal & Combined • AI Vision Scanner',
    editAccountModalTitle: 'Edit Financial Account',
    addAccountModalTitle: 'Add New Account',
    accountScopeLabel: 'Account Scope:',
    scopePersonalSub: 'Use for personal finance recording.',
    scopeBusinessSub: 'Use specifically for SME business operations.',
    scopeCombinedSub: 'Used jointly for personal and business transactions.',
    businessNameLabel: 'Business / Unit Name:',
    businessNamePlaceholder: 'e.g. Grocery Store, Express Laundry, Clothing Shop',
    selectRegisteredBusiness: 'Select from registered businesses:',
    accountNameLabel: 'Account Name:',
    accountNamePlaceholder: 'e.g. Store Cash, BCA Bank, ShopeePay',
    accountTypeLabel: 'Account Type:',
    cashTypeOpt: 'Petty Cash',
    bankTypeOpt: 'Bank Account',
    ewalletTypeOpt: 'E-Wallet',
    accountNumOptLabel: 'Account / Mobile Number (Optional):',
    initialBalanceLabel: 'Initial Balance:',
    accountsList: 'Cash & Accounts List',
    addAccount: '+ Add Cash / Account',
    editAccount: 'Edit Account',
    accountName: 'Account / Cash Name',
    accountType: 'Account Type',
    initialBalance: 'Initial Balance',
    scope: 'Account Scope',
    cashType: 'Petty Cash',
    bankType: 'Bank Account',
    walletType: 'E-Wallet',
    businessType: 'Business Cash',
    saveAccount: 'Save Account',

    // Toast Messages
    dataExported: 'Data successfully exported to Excel/CSV!',
    backupCompleted: 'Cloud backup successfully saved!',
    langChanged: 'Language changed to English',
  },
};

export type TranslationKey = keyof typeof translations.id;

export const CATEGORY_TRANSLATIONS: Record<string, { id: string; en: string }> = {
  'Makanan & Minuman': { id: 'Makanan & Minuman', en: 'Food & Dining' },
  'Transport': { id: 'Transport', en: 'Transport' },
  'Belanja': { id: 'Belanja', en: 'Shopping' },
  'Tagihan': { id: 'Tagihan', en: 'Bills & Utilities' },
  'Kesehatan': { id: 'Kesehatan', en: 'Health & Medical' },
  'Pendidikan': { id: 'Pendidikan', en: 'Education' },
  'Hiburan': { id: 'Hiburan', en: 'Entertainment' },
  'Bahan Baku/Stok': { id: 'Bahan Baku/Stok', en: 'Inventory & Stock' },
  'Gaji Karyawan': { id: 'Gaji Karyawan', en: 'Employee Salaries' },
  'Sewa Tempat': { id: 'Sewa Tempat', en: 'Rent & Venue' },
  'Operasional': { id: 'Operasional', en: 'Operations' },
  'Pemasaran & Promo': { id: 'Pemasaran & Promo', en: 'Marketing & Promo' },
  'Lain-lain': { id: 'Lain-lain', en: 'Other' },
  'Gaji/Upah': { id: 'Gaji/Upah', en: 'Salary / Wages' },
  'Penjualan': { id: 'Penjualan', en: 'Sales Income' },
  'Transfer Masuk': { id: 'Transfer Masuk', en: 'Transfer In' },
  'Bonus': { id: 'Bonus', en: 'Bonus' },
  'Modal Tambahan': { id: 'Modal Tambahan', en: 'Additional Capital' },
  'Pembayaran Hutang & Cicilan': { id: 'Pembayaran Hutang & Cicilan', en: 'Debt & Loan Repayment' },
  'Pemberian Pinjaman (Piutang Diberikan)': { id: 'Pemberian Pinjaman (Piutang Diberikan)', en: 'Lending / Receivables Issued' },
  'Penerimaan Pinjaman / Hutang Baru': { id: 'Penerimaan Pinjaman / Hutang Baru', en: 'New Loan / Debt Received' },
  'Penerimaan Pelunasan Piutang': { id: 'Penerimaan Pelunasan Piutang', en: 'Receivables Collected' },
};

export function getCategoryDisplayName(nameInput: any, lang: Language): string {
  if (!nameInput) return '';
  const name = typeof nameInput === 'object' && nameInput.name ? String(nameInput.name) : String(nameInput);
  if (lang === 'en' && CATEGORY_TRANSLATIONS[name]) {
    return CATEGORY_TRANSLATIONS[name].en;
  }
  return name;
}

export function getBudgetDisplayName(nameInput: string, lang: Language): string {
  if (!nameInput) return '';
  if (lang === 'en') {
    let result = nameInput;
    result = result.replace(/^Anggaran\s+/i, 'Budget ');
    result = result
      .replace(/\bJanuari\b/gi, 'January')
      .replace(/\bFebruari\b/gi, 'February')
      .replace(/\bMaret\b/gi, 'March')
      .replace(/\bMei\b/gi, 'May')
      .replace(/\bJuni\b/gi, 'June')
      .replace(/\bJuli\b/gi, 'July')
      .replace(/\bAgustus\b/gi, 'August')
      .replace(/\bOktober\b/gi, 'October')
      .replace(/\bDesember\b/gi, 'December');
    return result;
  } else {
    let result = nameInput;
    result = result.replace(/^Budget\s+/i, 'Anggaran ');
    result = result
      .replace(/\bJanuary\b/gi, 'Januari')
      .replace(/\bFebruary\b/gi, 'Februari')
      .replace(/\bMarch\b/gi, 'Maret')
      .replace(/\bMay\b/gi, 'Mei')
      .replace(/\bJune\b/gi, 'Juni')
      .replace(/\bJuly\b/gi, 'Juli')
      .replace(/\bAugust\b/gi, 'Agustus')
      .replace(/\bOctober\b/gi, 'Oktober')
      .replace(/\bDecember\b/gi, 'Desember');
    return result;
  }
}

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: string;
  setCurrency: (curr: string) => void;
  formatCurrency: (amount: number) => string;
  formatRupiah: (amount: number) => string;
  t: (key: TranslationKey) => string;
  getCategoryDisplayName: (name: string) => string;
  getBudgetDisplayName: (name: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('sakuku_lang');
    return (saved === 'en' || saved === 'id') ? saved : 'id';
  });

  const [currency, setCurrencyState] = useState<string>(() => {
    const saved = localStorage.getItem('sakuku_currency');
    return saved || 'IDR';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('sakuku_lang', lang);
  };

  const setCurrency = (curr: string) => {
    setCurrencyState(curr);
    localStorage.setItem('sakuku_currency', curr);
  };

  const formatCurrencyBound = (amount: number): string => {
    return formatCurrencyUtil(amount, currency);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.id[key] || key;
  };

  const getCategoryDisplayNameBound = (name: string): string => {
    return getCategoryDisplayName(name, language);
  };

  const getBudgetDisplayNameBound = (name: string): string => {
    return getBudgetDisplayName(name, language);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currency,
        setCurrency,
        formatCurrency: formatCurrencyBound,
        formatRupiah: formatCurrencyBound,
        t,
        getCategoryDisplayName: getCategoryDisplayNameBound,
        getBudgetDisplayName: getBudgetDisplayNameBound,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

